version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: hashland-api
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=8080
      - MONGO_URI=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:27017/main?authSource=admin
      - REDIS_URI=redis://redis:6379
      - REDIS_PRIMARY_ONLY=true
      - DATABASE_NAME=main
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=24h
      - TON_API_ENDPOINT=https://toncenter.com/api/v2/jsonRPC
    depends_on:
      - mongo
      - redis
    command: npm run start:dev
    env_file:
      - .env

  mongo:
    image: mongo:latest
    container_name: hashland-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=main
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    command: mongod --bind_ip_all --auth
    env_file:
      - .env

  redis:
    image: redis:alpine
    container_name: hashland-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --replica-read-only no

volumes:
  mongo-data:
  redis-data: 