FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
COPY tsconfig*.json ./
COPY nest-cli.json ./

# Clear npm cache and install dependencies
RUN npm cache clean --force
RUN npm ci

COPY . .

EXPOSE 8080

CMD ["npm", "run", "start:dev"] 