FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
COPY tsconfig*.json ./
COPY nest-cli.json ./

RUN npm install

COPY . .

COPY /app/node_modules ./node_modules
COPY package*.json ./
COPY tsconfig*.json ./

EXPOSE 8080

CMD ["npm", "run", "start:dev"] 