name: Development Deployment

on:
  push:
    branches:
      - dev
    tags:
      - 'development'
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    environment: development
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/hashland-api:dev -f Dockerfile.dev .
          docker build -t ${{ secrets.DOCKER_USERNAME }}/hashland-api:development -f Dockerfile.dev .
          docker push ${{ secrets.DOCKER_USERNAME }}/hashland-api:dev
          docker push ${{ secrets.DOCKER_USERNAME }}/hashland-api:development

  deploy:
    needs: build
    runs-on: self-hosted
    environment: development
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Create .env file
        run: |
          echo "ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}" > .env
          echo "DATABASE_NAME=main" >> .env
          echo "JWT_EXPIRATION=24h" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "MONGO_URI=mongodb://mongo:27017/main" >> .env
          echo "PORT=8080" >> .env
          echo "REDIS_URI=redis://redis:6379" >> .env
          echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> .env
          echo "TON_API_KEY=${{ secrets.TON_API_KEY }}" >> .env
          echo "TON_API_ENDPOINT=${{ secrets.TON_API_ENDPOINT }}" >> .env
          echo "ALCHEMY_API_KEY=${{ secrets.ALCHEMY_API_KEY }}" >> .env
          echo "TON_RECEIVER_ADDRESS=${{ secrets.TON_RECEIVER_ADDRESS }}" >> .env
          echo "TON_X_API_KEY=${{ secrets.TON_X_API_KEY }}" >> .env
          echo "NODE_ENV=development" >> .env
          echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> .env
      
      - name: Modify docker-compose for pre-built image
        run: |
          sed -i "s|dockerfile: Dockerfile.dev|image: ${{ secrets.DOCKER_USERNAME }}/hashland-api:development|g" docker-compose.yml
      
      - name: Deploy with docker-compose
        run: |
          docker compose down
          docker compose up -d 