name: Production Deployment

on:
  push:
    branches:
      - main
    tags:
      - 'production'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted
    environment: production
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/hashland-api:latest -f Dockerfile .
          docker build -t ${{ secrets.DOCKER_USERNAME }}/hashland-api:production -f Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/hashland-api:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/hashland-api:production
      
      - name: Create .env file
        run: |
          echo "ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}" > .env
          echo "DATABASE_NAME=main" >> .env
          echo "JWT_EXPIRATION=24h" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env
          echo "PORT=8080" >> .env
          echo "REDIS_URI=${{ secrets.REDIS_URI }}" >> .env
          echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> .env
          echo "TON_API_KEY=${{ secrets.TON_API_KEY }}" >> .env
          echo "TON_API_ENDPOINT=${{ secrets.TON_API_ENDPOINT }}" >> .env
          echo "ALCHEMY_API_KEY=${{ secrets.ALCHEMY_API_KEY }}" >> .env
          echo "TON_RECEIVER_ADDRESS=${{ secrets.TON_RECEIVER_ADDRESS }}" >> .env
          echo "TON_X_API_KEY=${{ secrets.TON_X_API_KEY }}" >> .env
          echo "NODE_ENV=production" >> .env
      
      - name: Deploy container
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/hashland-api:production
          docker stop hashland-api || true
          docker rm hashland-api || true
          docker run -d --name hashland-api \
            --restart unless-stopped \
            -p 8080:8080 \
            --env-file .env \
            ${{ secrets.DOCKER_USERNAME }}/hashland-api:production 