/**
 * Represents the shop items available for purchase.
 */
export enum ShopItemType {
  IRONBORE_DRILL = 'IRONBORE_DRILL',
  BULWARK_DRILL = 'BULWARK_DRILL',
  TITAN_DRILL = 'TITAN_DRILL',
  DREADNOUGHT_DRILL = 'DREADNOUGHT_DRILL',
  UPGRADE_MAX_FUEL = 'UPGRADE_MAX_FUEL',
  REPLENISH_FUEL = 'REPLENISH_FUEL',
}
